//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@interface BasePackage : NSObject
{
    unsigned char _type;
    _Bool _hasPayLoads;
    _Bool _sync;
    _Bool _ack;
    _Bool _needAck;
    unsigned char _version;
    unsigned int _msgPackLength;
    unsigned int _localId;
    double _sendTimestamp;
}

+ (id)messageTypeStringWithType:(long long)arg1;
+ (id)parsePackage:(id)arg1;
+ (unsigned int)parsePayloadsMsgPackLength:(id)arg1;
+ (_Bool)parseHeaderHasPayLoads:(id)arg1;
+ (unsigned long long)getMessageIDFromData:(id)arg1 startIndex:(unsigned int)arg2;
+ (unsigned int)getuintWithData:(id)arg1 start:(unsigned int)arg2;
+ (Class)classFromType:(unsigned char)arg1 isAck:(_Bool)arg2;
+ (id)uint64ToData:(unsigned long long)arg1;
+ (id)uintToData:(unsigned int)arg1;
+ (id)uint8ToData:(unsigned char)arg1;
@property(nonatomic) unsigned int localId; // @synthesize localId=_localId;
@property(nonatomic) double sendTimestamp; // @synthesize sendTimestamp=_sendTimestamp;
@property(nonatomic) unsigned int msgPackLength; // @synthesize msgPackLength=_msgPackLength;
@property(nonatomic) unsigned char version; // @synthesize version=_version;
@property(nonatomic) _Bool needAck; // @synthesize needAck=_needAck;
@property(nonatomic) _Bool ack; // @synthesize ack=_ack;
@property(nonatomic) _Bool sync; // @synthesize sync=_sync;
@property(nonatomic) _Bool hasPayLoads; // @synthesize hasPayLoads=_hasPayLoads;
@property(nonatomic) unsigned char type; // @synthesize type=_type;
- (id)msgPackToByte;
- (void)parseMsgPack:(id)arg1 start:(unsigned int)arg2;
- (id)toBype;
- (void)parsePayLoads:(id)arg1 start:(unsigned int)arg2;
- (void)parseHeader:(unsigned char)arg1;
- (void)parseWithAllData:(id)arg1;
- (id)description;

@end

