//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//
#import <UIKit/UIKit.h>
//#import "BDMsgExtraSystemViewDelegate.h"

//@class BDMsgSrcView, GJIMMessageModel, NSDictionary, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel, UIView;
@class GJIMMessageModel, NSDictionary, NSLayoutConstraint, NSString, UIButton, UIImageView, UILabel, UIView;

@interface BDChatBasicCell : UITableViewCell
{
    unsigned int _vip_grade;
    unsigned int _vip_annual;
    unsigned int _vip_exp_lvl;
//    id <ChatBasicCellDelegate> _delegate;
    UILabel *_sendTimeLabel;
    UIButton *_selfAvatarImg;
    UIButton *_otherAvatarImg;
    NSLayoutConstraint *_topToConetentHeight;
    NSLayoutConstraint *_singleLineBubbleHeight;
    NSLayoutConstraint *_avatarTop;
    NSLayoutConstraint *_timeLabelTop;
    NSLayoutConstraint *_timeLabelHeight;
    GJIMMessageModel *_message;
    UILabel *_groupNormalNameLabel;
    UILabel *_groupManagerNameLabel;
    UILabel *_distanceLabel;
    UIView *_distanceView;
    NSLayoutConstraint *_groupChatTopConstraint;
//    BDMsgSrcView *_srcView;
    NSLayoutConstraint *_spaceBubbleAvatar;
    NSDictionary *_selfBubbleDic;
    NSDictionary *_otherBubbleDic;
    UIImageView *_messageSendingImgView;
    UILabel *_messageSendStatusLabel;
    UIImageView *_sendFaildImgView;
    UIImageView *_vbadgeView;
    UILabel *_groupRoleLabel;
    NSLayoutConstraint *_groupRoleLabWidth;
    NSLayoutConstraint *_groupRoleLabHeight;
    UIImageView *_ivVipIcon;
    UIView *_privateDistanceView;
    UIImageView *_bubbleImgView;
    NSLayoutConstraint *_contentViewBottom;
    NSLayoutConstraint *_avatarHeight;
}

+ (id)cellReuseID;
+ (_Bool)judgeIfisOfficalAccountMessage:(id)arg1;
+ (id)dequeueReusableCellForTableView:(id)arg1 message:(id)arg2;
+ (void)registerChatCellNibForTableView:(id)arg1;
//- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *avatarHeight; // @synthesize avatarHeight=_avatarHeight;
@property(nonatomic) __weak NSLayoutConstraint *contentViewBottom; // @synthesize contentViewBottom=_contentViewBottom;
@property(retain, nonatomic) UIImageView *bubbleImgView; // @synthesize bubbleImgView=_bubbleImgView;
@property(retain, nonatomic) UIView *privateDistanceView; // @synthesize privateDistanceView=_privateDistanceView;
@property(retain, nonatomic) UIImageView *ivVipIcon; // @synthesize ivVipIcon=_ivVipIcon;
@property(nonatomic) __weak NSLayoutConstraint *groupRoleLabHeight; // @synthesize groupRoleLabHeight=_groupRoleLabHeight;
@property(nonatomic) __weak NSLayoutConstraint *groupRoleLabWidth; // @synthesize groupRoleLabWidth=_groupRoleLabWidth;
@property(nonatomic) __weak UILabel *groupRoleLabel; // @synthesize groupRoleLabel=_groupRoleLabel;
@property(nonatomic) __weak UIImageView *vbadgeView; // @synthesize vbadgeView=_vbadgeView;
@property(nonatomic) __weak UIImageView *sendFaildImgView; // @synthesize sendFaildImgView=_sendFaildImgView;
@property(nonatomic) __weak UILabel *messageSendStatusLabel; // @synthesize messageSendStatusLabel=_messageSendStatusLabel;
@property(nonatomic) __weak UIImageView *messageSendingImgView; // @synthesize messageSendingImgView=_messageSendingImgView;
@property(retain, nonatomic) NSDictionary *otherBubbleDic; // @synthesize otherBubbleDic=_otherBubbleDic;
@property(retain, nonatomic) NSDictionary *selfBubbleDic; // @synthesize selfBubbleDic=_selfBubbleDic;
@property(nonatomic) __weak NSLayoutConstraint *spaceBubbleAvatar; // @synthesize spaceBubbleAvatar=_spaceBubbleAvatar;
//@property(retain, nonatomic) BDMsgSrcView *srcView; // @synthesize srcView=_srcView;
@property(nonatomic) __weak NSLayoutConstraint *groupChatTopConstraint; // @synthesize groupChatTopConstraint=_groupChatTopConstraint;
@property(nonatomic) unsigned int vip_exp_lvl; // @synthesize vip_exp_lvl=_vip_exp_lvl;
@property(nonatomic) unsigned int vip_annual; // @synthesize vip_annual=_vip_annual;
@property(nonatomic) unsigned int vip_grade; // @synthesize vip_grade=_vip_grade;
@property(retain, nonatomic) UIView *distanceView; // @synthesize distanceView=_distanceView;
@property(retain, nonatomic) UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(nonatomic) __weak UILabel *groupManagerNameLabel; // @synthesize groupManagerNameLabel=_groupManagerNameLabel;
@property(nonatomic) __weak UILabel *groupNormalNameLabel; // @synthesize groupNormalNameLabel=_groupNormalNameLabel;
@property(retain, nonatomic) GJIMMessageModel *message; // @synthesize message=_message;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelHeight; // @synthesize timeLabelHeight=_timeLabelHeight;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelTop; // @synthesize timeLabelTop=_timeLabelTop;
@property(nonatomic) __weak NSLayoutConstraint *avatarTop; // @synthesize avatarTop=_avatarTop;
@property(nonatomic) __weak NSLayoutConstraint *singleLineBubbleHeight; // @synthesize singleLineBubbleHeight=_singleLineBubbleHeight;
@property(nonatomic) __weak NSLayoutConstraint *topToConetentHeight; // @synthesize topToConetentHeight=_topToConetentHeight;
@property(nonatomic) __weak UIButton *otherAvatarImg; // @synthesize otherAvatarImg=_otherAvatarImg;
@property(nonatomic) __weak UIButton *selfAvatarImg; // @synthesize selfAvatarImg=_selfAvatarImg;
@property(nonatomic) __weak UILabel *sendTimeLabel; // @synthesize sendTimeLabel=_sendTimeLabel;
//@property(nonatomic) __weak id <ChatBasicCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)showMessageSourceView:(id)arg1;
- (void)setContentviewBottomSpace:(double)arg1;
- (id)resizeImageScale:(id)arg1 imageKey:(id)arg2;
//- (void)setUpBubbleImageView:(long long)arg1 safeViewHeight:(double)arg2 compete:(CDUnknownBlockType)arg3;
- (_Bool)shouldShowMessageSourceView;
- (void)didHideFaileImageView;
- (void)didHideEditMenu:(id)arg1;
- (void)reSendPressed:(id)arg1;
- (void)longpressOnAvatar:(id)arg1;
- (void)avatarBtnAction:(id)arg1;
- (void)setupVipIcon;
- (void)setupData;
- (void)prepareForReuse;
- (void)awakeFromNib;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

