//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface BDEncrypt : NSObject
{
}

+ (id)encryptDeviceID;
+ (id)encryptVideoCoverUrl:(id)arg1;
+ (id)decryptVideoUrl:(id)arg1;
+ (id)encryptTokenForIM:(id)arg1;
+ (id)encryptToken:(id)arg1;
+ (id)decryptParameters:(id)arg1;
+ (id)encryptParameters:(id)arg1;
+ (id)encryptUidForCookie:(id)arg1;
+ (id)encryptDVID:(id)arg1;
+ (id)decryptID:(id)arg1;
+ (id)encryptID:(id)arg1;
+ (id)SHA1String:(id)arg1;
+ (id)MD5String:(id)arg1;

@end

