//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@interface GJIMSessionToken : NSObject
{
    unsigned char _sessionType;
    unsigned int _sessionId;
}

+ (id)gji_sessionTokenWithId:(unsigned int)arg1 type:(unsigned char)arg2;
@property(nonatomic) unsigned int sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned char sessionType; // @synthesize sessionType=_sessionType;
- (id)gji_string;

@end

