//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@class GJIMSessionToken, NSString;

@interface GJIMBaseModel : NSObject <NSCopying>
{
    unsigned char _sessionType;
    unsigned int _sessionId;
    GJIMSessionToken *_sessionToken;
    NSString *_avatar;
}

//- (void).cxx_destruct;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) unsigned int sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned char sessionType; // @synthesize sessionType=_sessionType;
@property(readonly, nonatomic) GJIMSessionToken *sessionToken; // @synthesize sessionToken=_sessionToken;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

