//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//#import "NSObject.h"

@class GJIMSessionToken, NSMutableArray;

@interface GJIMMessageService : NSObject
{
    _Bool _isPeep;
    _Bool _im_isSearching;
    GJIMSessionToken *_sessionToken;
//    id <GJIMMessageServiceDelegate> _delegate;
    NSMutableArray *_messageArr;
}

//- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *messageArr; // @synthesize messageArr=_messageArr;
@property(nonatomic) _Bool im_isSearching; // @synthesize im_isSearching=_im_isSearching;
@property(nonatomic) _Bool isPeep; // @synthesize isPeep=_isPeep;
//@property(nonatomic) __weak id <GJIMMessageServiceDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) GJIMSessionToken *sessionToken; // @synthesize sessionToken=_sessionToken;
//- (void)p_checkIfSearching:(CDUnknownBlockType)arg1;
- (void)p_handleSyncRangeMessages:(id)arg1 syncType:(unsigned long long)arg2;
- (id)p_findLeakMessageIdsWithMessages:(id)arg1;
- (void)p_notifyDelegate:(unsigned long long)arg1;
- (_Bool)p_isAllDeleted:(id)arg1;
- (id)p_filterDeletedMessages:(id)arg1;
- (id)p_sortAndUniqMessages:(id)arg1 descend:(_Bool)arg2;
- (id)latestUnDelMessage;
- (id)latestMessage;
- (id)messageWithMessageId:(unsigned long long)arg1;
- (void)addMessages:(id)arg1;
- (void)deleteMessage:(id)arg1;
- (void)updateGroupMember:(id)arg1;
- (void)updateMessagesToReadedWithMessageId:(unsigned long long)arg1;
- (void)updateMessage:(id)arg1;
- (void)addMessage:(id)arg1;
- (void)clearMessages;
- (id)strOfTenMessagesWithIndex:(unsigned long long)arg1;
- (void)fetchMoreMessagesFromMessage:(id)arg1 isDown:(_Bool)arg2;
- (void)fetchMoreMessages;
- (void)fetchMessagesWithStartMsgId:(unsigned long long)arg1 endMsgId:(unsigned long long)arg2;
- (void)fetchLeakMessages;
- (void)fetchMessages;
- (id)initWithSessionToken:(id)arg1;

@end

