//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <Foundation/Foundation.h>

//@class FMDatabaseQueue, NSObject<OS_dispatch_semaphore>;

@interface GJIMDBService : NSObject
{
//    FMDatabaseQueue *_dbQueue;
    NSObject<OS_dispatch_semaphore> *_dbQueueLock;
}

+ (void)releaseInstance;
+ (id)sharedGJIMDBService;
//+ (void)gji_searchKeyword:(id)arg1 token:(id)arg2 resultSet:(id)arg3 page:(unsigned long long)arg4 pageSize:(unsigned long long)arg5 complete:(CDUnknownBlockType)arg6;
//+ (void)gji_searchKeyword:(id)arg1 complete:(CDUnknownBlockType)arg2;
+ (void)gji_updateMessageReadedFromMaxMessage:(id)arg1;
+ (void)gji_updateMessage:(id)arg1;
+ (void)gji_deleteAllMessagesForAllSessions;
+ (void)gji_deleteAllMessagesForSessionWithToken:(id)arg1;
+ (void)gji_deleteAMessageForSession:(id)arg1 msgId:(unsigned long long)arg2 msgLocalId:(unsigned int)arg3;
//+ (void)gji_insertForMessages:(id)arg1 complete:(CDUnknownBlockType)arg2;
+ (void)gji_insertForMessages:(id)arg1;
+ (id)gji_messageWithToken:(id)arg1 msgId:(unsigned long long)arg2;
+ (void)gji_getMessagesWithToken:(id)arg1 startMsgId:(unsigned long long)arg2 endMsgId:(unsigned long long)arg3 complete:(id)arg4;
+ (void)gji_getMessagesWithToken:(id)arg1 msgId:(unsigned long long)arg2 localId:(unsigned int)arg3 sendTime:(unsigned int)arg4 isDown:(_Bool)arg5 complete:(id)arg6;
+ (void)gji_getMessagesWithToken:(id)arg1 complete:(id)arg2;
+ (void)gji_deleteAllSessions;
+ (void)gji_deleteSessionWithToken:(id)arg1;
+ (void)gji_closeIMDB;
//+ (void)gji_updateForNotifySessions:(id)arg1 complete:(CDUnknownBlockType)arg2;
+ (void)gji_updateSessionsMaxMessageId:(id)arg1;
//+ (void)gji_updateForSessions:(id)arg1 complete:(CDUnknownBlockType)arg2;
+ (id)gji_getNotifySessionWithType:(unsigned char)arg1;
//+ (void)gji_getNotifySessionWithType:(unsigned char)arg1 result:(CDUnknownBlockType)arg2;
//+ (void)gji_getChatSession:(CDUnknownBlockType)arg1;
//- (void).cxx_destruct;
@property(retain, nonatomic) NSObject<OS_dispatch_semaphore> *dbQueueLock; // @synthesize dbQueueLock=_dbQueueLock;
- (id)p_filterDuplicateData:(id)arg1;
//- (void)p_searchKeyword:(id)arg1 token:(id)arg2 resultSet:(id)arg3 page:(unsigned long long)arg4 pageSize:(unsigned long long)arg5 complete:(CDUnknownBlockType)arg6;
//- (void)p_searchKeyword:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (_Bool)p_hasExistSessionForToken:(id)arg1 db:(id)arg2;
- (void)p_InternationalDBVersion8_9:(id)arg1;
- (void)p_InternationalDBVersion7_8:(id)arg1;
- (void)p_InternationalDBVersion6_7:(id)arg1;
- (void)p_InternationalDBVersion5_6:(id)arg1;
- (void)p_InternationalDBVersion4_5:(id)arg1;
- (void)p_InternationalDBVersion2_4:(id)arg1;
- (void)p_InternationalDBVersion0_2:(id)arg1;
- (void)p_initInternationalMessageTable:(id)arg1;
- (void)p_dBVersion9_10:(id)arg1;
- (void)p_dBVersion8_9:(id)arg1;
- (void)p_dBVersion7_8:(id)arg1;
- (void)p_dBVersion6_7:(id)arg1;
- (void)p_dBVersion5_6:(id)arg1;
- (void)p_dBVersion2_3:(id)arg1;
- (void)p_dBVersion1_2:(id)arg1;
- (void)p_dBVersion0_1:(id)arg1;
- (void)p_initMessageTable:(id)arg1;
- (void)p_initSessionTable:(id)arg1;
- (void)p_initTables;
- (void)p_updateMessageReadedFromMaxMessage:(id)arg1;
- (void)p_updateMessage:(id)arg1;
- (void)p_deleteMessageForSession:(id)arg1 msgId:(unsigned long long)arg2 msgLocalId:(unsigned int)arg3;
//- (void)p_insertForMessages:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)p_insertForMessages:(id)arg1;
- (id)p_messageWithToken:(id)arg1 msgId:(unsigned long long)arg2;
//- (void)p_getMessagesWithToken:(id)arg1 startMsgId:(unsigned long long)arg2 endMsgId:(unsigned long long)arg3 complete:(CDUnknownBlockType)arg4;
//- (void)p_getMessagesWithToken:(id)arg1 msgId:(unsigned long long)arg2 localId:(unsigned int)arg3 sendTime:(unsigned int)arg4 isDown:(_Bool)arg5 complete:(CDUnknownBlockType)arg6;
- (void)p_getMessagesWithToken:(id)arg1 complete:(id)arg2;
- (void)p_deleteSessionWithToken:(id)arg1;
- (void)p_updateSessionMaxMessageId:(id)arg1;
//- (void)p_updateForSessions:(id)arg1 complete:(CDUnknownBlockType)arg2;
//- (void)p_updateForNotifySessions:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (id)p_getNotifySessionWithID:(unsigned int)arg1;
//- (void)p_getNotifySessionWithID:(unsigned int)arg1 callback:(CDUnknownBlockType)arg2;
//- (void)p_getChatSession:(CDUnknownBlockType)arg1;
- (id)p_startService;

@end

