//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePackage.h"

@class MsgHeader, NSDictionary, NSString;

@interface PushPackage : BasePackage
{
    unsigned char _sessionType;
    unsigned char _app;
    _Bool _isMute;
    unsigned int _sessionId;
    unsigned int _timestamp;
    unsigned int _from;
    unsigned int _session_status;
    unsigned int _vbadge;
    unsigned int _vip_grade;
    unsigned int _vip_annual;
    unsigned int _vip_exp_lvl;
    int _is_hide_vip_look;
    unsigned int _isfriend;
    unsigned int _rich_level;
    unsigned int _o_rich_level;
    unsigned int _is_manager;
    unsigned int _totalTime;
    int _online;
    int _hasScreenshot;
    unsigned int _o_vip_grade;
    int _o_is_hide_vip_look;
    int _o_face_status;
    int _is_open_privilege;
    int _fan_club_badge_hidden;
    MsgHeader *_header;
    unsigned long long _messageId;
    NSString *_distance;
    unsigned long long _messageType;
    NSString *_at;
    NSString *_contents;
    NSString *_name;
    NSString *_avatar;
    NSDictionary *_msgExtra;
    unsigned long long _closeType;
    NSString *_roomId;
    unsigned long long _roomType;
    NSString *_avatar_pendant;
    NSString *_is_hot_card;
    NSString *_wealth_privilege_uid;
}

+ (id)securityMessageKey:(id)arg1;
+ (id)parsePushPackagesWithData:(id)arg1;
//- (void).cxx_destruct;
@property(nonatomic) int fan_club_badge_hidden; // @synthesize fan_club_badge_hidden=_fan_club_badge_hidden;
@property(retain, nonatomic) NSString *wealth_privilege_uid; // @synthesize wealth_privilege_uid=_wealth_privilege_uid;
@property(nonatomic) int is_open_privilege; // @synthesize is_open_privilege=_is_open_privilege;
@property(nonatomic) int o_face_status; // @synthesize o_face_status=_o_face_status;
@property(retain, nonatomic) NSString *is_hot_card; // @synthesize is_hot_card=_is_hot_card;
@property(retain, nonatomic) NSString *avatar_pendant; // @synthesize avatar_pendant=_avatar_pendant;
@property(nonatomic) int o_is_hide_vip_look; // @synthesize o_is_hide_vip_look=_o_is_hide_vip_look;
@property(nonatomic) unsigned int o_vip_grade; // @synthesize o_vip_grade=_o_vip_grade;
@property(nonatomic) _Bool isMute; // @synthesize isMute=_isMute;
@property(nonatomic) int hasScreenshot; // @synthesize hasScreenshot=_hasScreenshot;
@property(nonatomic) int online; // @synthesize online=_online;
@property(nonatomic) unsigned int totalTime; // @synthesize totalTime=_totalTime;
@property(nonatomic) unsigned long long roomType; // @synthesize roomType=_roomType;
@property(retain, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(nonatomic) unsigned long long closeType; // @synthesize closeType=_closeType;
@property(nonatomic) unsigned int is_manager; // @synthesize is_manager=_is_manager;
@property(nonatomic) unsigned int o_rich_level; // @synthesize o_rich_level=_o_rich_level;
@property(nonatomic) unsigned int rich_level; // @synthesize rich_level=_rich_level;
@property(nonatomic) unsigned int isfriend; // @synthesize isfriend=_isfriend;
@property(nonatomic) int is_hide_vip_look; // @synthesize is_hide_vip_look=_is_hide_vip_look;
@property(nonatomic) unsigned int vip_exp_lvl; // @synthesize vip_exp_lvl=_vip_exp_lvl;
@property(nonatomic) unsigned int vip_annual; // @synthesize vip_annual=_vip_annual;
@property(nonatomic) unsigned int vip_grade; // @synthesize vip_grade=_vip_grade;
@property(nonatomic) unsigned int vbadge; // @synthesize vbadge=_vbadge;
@property(retain, nonatomic) NSDictionary *msgExtra; // @synthesize msgExtra=_msgExtra;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *contents; // @synthesize contents=_contents;
@property(nonatomic) unsigned int session_status; // @synthesize session_status=_session_status;
@property(nonatomic) unsigned int from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *at; // @synthesize at=_at;
@property(nonatomic) unsigned char app; // @synthesize app=_app;
@property(nonatomic) unsigned long long messageType; // @synthesize messageType=_messageType;
@property(retain, nonatomic) NSString *distance; // @synthesize distance=_distance;
@property(nonatomic) unsigned int timestamp; // @synthesize timestamp=_timestamp;
@property(nonatomic) unsigned long long messageId; // @synthesize messageId=_messageId;
@property(nonatomic) unsigned int sessionId; // @synthesize sessionId=_sessionId;
@property(nonatomic) unsigned char sessionType; // @synthesize sessionType=_sessionType;
@property(retain, nonatomic) MsgHeader *header; // @synthesize header=_header;
- (id)getBestMatchContents:(id)arg1;
- (void)parseMsgPack:(id)arg1 start:(unsigned int)arg2;
@property(readonly, nonatomic) _Bool isMyGroupChat;
@property(readonly, nonatomic) _Bool isMyPraviteChat;

@end

